<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<!-- File extensions commented out here so that the main
		`gcode` highligher gets used by default instead of this one!
		<string>eia</string>
		<string>nc</string>
		<string>ngc</string>
		<string>prg</string>
		<string>mpf</string>
		<string>gcode</string>
		-->
	</array>
	<key>name</key>
	<string>gcode-alternate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>G 28</string>
			<key>match</key>
			<string>(G28)|(G5[1-9](\.)\d+)|(G5[1-9])</string>
			<key>name</key>
			<string>markup.bold.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G other</string>
			<key>match</key>
			<string>(G)((\.)|(\d))+</string>
			<key>name</key>
			<string>storage.cnc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.cnc</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>markup.bold.cnc</string>
				</dict>
			</dict>
			<key>comment</key>
			<false/>
			<key>match</key>
			<string>([PQR])((\.)|(\d)|(\-|\+))+</string>
			<key>name</key>
			<string>string.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>op. number</string>
			<key>match</key>
			<string>(\b[O]([\d\.-])+)</string>
			<key>name</key>
			<string>invalid.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tool</string>
			<key>match</key>
			<string>T((\d))+</string>
			<key>name</key>
			<string>keyword.control.def.ruby</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.cnc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>axes</string>
			<key>match</key>
			<string>([ZABC])((\.)|(\d)|(\-|\+))+</string>
			<key>name</key>
			<string>string.cnc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.changed.cnc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>axes</string>
			<key>match</key>
			<string>([XYUW])((\.)|(\d)|(\-|\+))+</string>
			<key>name</key>
			<string>string.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>.</string>
			<key>match</key>
			<string>([KJI]((\.)|(\d)|(\-))+)</string>
			<key>name</key>
			<string>meta.structure.dictionary.json string.quoted.double.json.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Feed/speed</string>
			<key>match</key>
			<string>([FS])((\.)|(\d)|(\-))+</string>
			<key>name</key>
			<string>constant.numeric.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>\(([^()]*)\)</string>
			<key>name</key>
			<string>comment.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>N</string>
			<key>match</key>
			<string>\bN\d+</string>
			<key>name</key>
			<string>comment.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G 28</string>
			<key>match</key>
			<string>\;.+</string>
			<key>name</key>
			<string>comment.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>M code</string>
			<key>match</key>
			<string>M((\.)|(\d)|(\-))+</string>
			<key>name</key>
			<string>entity.name.class.cnc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>brackets</string>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>string.cnc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cnc</string>
	<key>uuid</key>
	<string>877ff98b-b20a-4fbe-9cb8-af4369ea9b44</string>
</dict>
</plist>
